version: '3.7'

services:
  gw_app:
    container_name: gw_app
    build:
      context: .
      target: development
    volumes:
      - .:/src/app
      - /src/app/node_modules
    environment:
      JWT_SECRET:
      JWT_EXPIRATION:
      DB_HOST: mariadb
      DB_PORT:
      DB_USERNAME:
      DB_PASSWORD:
      DB_DATABASE:
    ports:
      - ${HOST_PORT}:${HOST_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
  mariadb:
    image: mariadb:10.5
    volumes:
      - gw-db:/var/lib/mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: gw-local
    ports:
      - 3306:3306
volumes:
  gw-db:
    