version: '3.7'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/src/app
      - /src/app/node_modules
    environment:
      JWT_SECRET:
      JWT_EXPIRATION:
      DB_HOST: mariadb
      DB_PORT: '3306'
      DB_USERNAME:
      DB_PASSWORD:
      DB_DATABASE:
    ports:
      - ${HOST_PORT}:${HOST_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
  mariadb:
    image: mariadb:10.5
    volumes:
      - gw-db:/var/lib/mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306
volumes:
  gw-db:
    